theme: jekyll-theme-minimal
title: ADA Website IG Nobel Laureates 
description: A template website for ADA
show_downloads: True
navigation:
  - title: HOME 
    url: /
  - title: STORY
    url: /
  - title: DATASETS
    url: /
  - title: TEAM
    url: /
  - title: CONCLUSION
    url: /
